print("QUESTION 21 starting..", "\n")

import turtle
turtle.showturtle()
turtle.circle(125)
turtle.write(6)
turtle.penup()
turtle.right(90)
turtle.forward(20)
turtle.write("9:15:00")
turtle.backward(20)
turtle.pendown()
turtle.left(90)
turtle.penup()
turtle.goto(125,125)
turtle.backward(10)
turtle.write(3)
turtle.forward(10)
turtle.goto(0,250)
turtle.right(90)
turtle.forward(15)
turtle.write(12)
turtle.backward(15)
turtle.left(90)
turtle.pendown()
turtle.penup()
turtle.goto(-125,125)
turtle.forward(15)
turtle.write(9)
turtle.backward(15)
turtle.pendown()
turtle.penup()
turtle.goto(0,125)
turtle.pendown()
turtle.color("blue")
turtle.forward(100)
turtle.backward(100)
turtle.left(90)
turtle.color("green")
turtle.forward(100)
turtle.backward(100)
turtle.color("red")
turtle.left(90)
turtle.forward(65)

turtle.done()